import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '700'], 
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ['400', '700'], 
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable} antialiased`}
        style={{
    background: "radial-gradient(125% 125% at 50% 100%, #000000 40%, #010133 100%)",
    minHeight: '100vh',
    width: '100%',
  }}
      >
        {children}
      </body>
    </html>
  );
}
